---
collections:
- beyondtrust.secrets_safe
# Install a collection from Ansible Galaxy.
#- name: beyondtrust.secrets_safe
#  version: ">=0.0.1"
#  source: https://galaxy.ansible.com

- source: ./beyondtrust-secrets_safe-1.0.0/
  type: dir