---
#####
# Stage 1 - BeyondTrust & Ansible Integration
#https://www.beyondtrust.com/docs/beyondinsight-password-safe/ps/integrations/ansible/index.htm
#https://github.com/emreyardimci/ansible-beyondtrust
#https://galaxy.ansible.com/ui/repo/published/beyondtrust/secrets_safe/

- hosts: localhost
  collections:
    - beyondtrust.secrets_safe
  gather_facts: no
  vars:
    apiURL: 'https://44.207.168.98:443/BeyondTrust/api/public/v3'
    clientIdFromEnvVar: '58c84ca3XXXXXXXXX-1308d73736b8' #"{{ lookup('ansible.builtin.env', 'PASSWORD_SAFE_CLIENT_ID') }}"
    secretFromEnvVar: '+cU/Ia++5oXXXXXXXXXXXXXXX+FTAlbM=' #"{{ lookup('ansible.builtin.env', 'PASSWORD_SAFE_CLIENT_SECRET') }}"
    secretManagedAccounts: 'quasys-domain/beyondtrust'
    
    gotManagedAccount: "{{lookup('beyondtrust.secrets_safe.secrets_safe_lookup', api_url=apiURL, retrieval_type='MANAGED_ACCOUNT', client_id=clientIdFromEnvVar, client_secret=secretFromEnvVar, secret_list=secretManagedAccounts, wantlist=False, verify_ca=False)}}"

  tasks:
   - name: BeyondTrust Collection Test
     shell: echo {{gotManagedAccount}}
     register: shell_result
     become: true
   - debug: msg="{{ shell_result.stdout.split('\n') }}"  
 