---
#####
# Stage 1 - Uninstall & Clear

- hosts: all
  collections:
    - cyberark.pas
  gather_facts: no
  vars:
  tasks:

   #- meta: end_play

   - name: BeyondTrust Collection Test
     shell: echo "I am dev"
     register: shell_result
     become: true
   - debug: msg="{{ shell_result.stdout.split('\n') }}"  
 